vc-dwim: diagnose an invalid "date  name  <email>" line
* vc-dwim.pl (main): Diagnose an invalid "date  name  <email>"
line and fail -- currently detects the cases of using a single
space instead of two spaces as separator.
* tests/cl-syntax: Test for these cases.
Reported by Karl Berry in http://bug.gnu.org/38862

diff --git a/tests/cl-syntax b/tests/cl-syntax
--- a/tests/cl-syntax
+++ b/tests/cl-syntax
@@ -32,4 +32,23 @@ fail=0
 echo a > foo || framework_failure_
 vc-dwim ChangeLog || fail=1
 
+# Ensure that we fail for a "date  name  email" line that uses
+# just one space for either separator.
+
+for invalid in \
+  '2011-05-31 R. Andom  <random@example.com>' \
+  '2011-05-31  R. Andom <random@example.com>'; do
+
+  printf '%s\n' \
+    "vc-dwim:ChangeLog: invalid 'date  name  <email>' line:" "+$invalid" \
+    > exp.err || framework_failure_
+
+  printf '%s\n' "$invalid" '' one-line '* foo: xx' > ChangeLog \
+    || framework_failure_
+
+  echo b > foo || framework_failure_
+  vc-dwim ChangeLog 2> err && fail=1
+  compare exp.err err || fail=1
+done
+
 Exit $fail
