vc-dwim: die if no one-line summary
* vc-dwim.pl (main): Die if no one-line summary,
and report actual first line found.
* NEWS: update.
* tests/subdir-cvs: Now expect this use of vc-dwim to fail.
Adjust expected error output.
* tests/add-empty: Initialize fail, and set it upon failure.
Also provide a summary line.
* tests/author-bzr: Provide a summary.
Set fail upon failure, rather than relying on set -e.
* tests/changelog-header-at-end-of-log: Likewise.
* tests/cl-syntax: Add summary.
Include leading TABs in recently-added example.
* tests/author: Add a summary in each.
* tests/git-mv: Likewise.
* tests/no-star: Likewise.
* tests/symlinked-changelog: Likewise.
* tests/scalar: Likewise.
* tests/two-line-attr: Likewise.

diff --git a/tests/subdir-cvs b/tests/subdir-cvs
--- a/tests/subdir-cvs
+++ b/tests/subdir-cvs
@@ -37,7 +37,7 @@ if cvs diff ChangeLog > /dev/null; then
   touch -d '2 seconds' f ChangeLog 2> /dev/null || sleep 2
 fi
 
-vc-dwim ChangeLog > out 2> err || fail=1
+vc-dwim ChangeLog > out 2> err && fail=1
 
 sed 's/RCS file:.*//;s/^[-+][-+][-+] f.*//' out > k; mv k out
 cat <<\EOF > exp || fail=1
@@ -55,7 +55,8 @@ EOF
 
 compare exp out || fail=1
 
-echo vc-dwim: ChangeLog: no one-line summary > exp.err || fail=1
+echo 'vc-dwim: ChangeLog: one-line summary not found; first line: * f: X.' \
+  > exp.err || fail=1
 compare exp.err err || fail=1
 
 Exit $fail
