* tests/trap-setup: Don't clean up if $DEBUG is set.

diff --git a/tests/trap-setup b/tests/trap-setup
--- a/tests/trap-setup
+++ b/tests/trap-setup
@@ -2,5 +2,9 @@
 
 pwd=`pwd`
 t0=`echo "$0"|sed 's,.*/,,'`.tmp; tmp=$t0/$$
-trap 'status=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $status' 0
-trap '(exit $?); exit $?' 1 2 13 15
+
+# Don't clean up if $DEBUG is set.
+if test "${DEBUG+set}" != set; then
+  trap 'st=$?; cd "$pwd" && chmod -R u+rwx $t0 && rm -rf $t0 && exit $st' 0
+  trap '(exit $?); exit $?' 1 2 13 15
+fi
